# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

###############################################################################
###                           Client Configuration                          ###
###############################################################################

# The network chain ID
chain-id = ""
# The keyring's backend, where the keys are stored (os|file|kwallet|pass|test|memory)
keyring-backend = "os"
# CLI output format (text|json)
output = "text"
# <host>:<port> to Tendermint RPC interface for this chain
node = "https://rpc.explorebitsong.com:443"
# Transaction broadcasting mode (sync|async|block)
broadcast-mode = "sync"

###############################################################################
###                          Bitsong Tx Configuration                          ###
###############################################################################

# Amount of gas per transaction
gas = ""
# Price per unit of gas (ex: 0.005uthiol)
gas-prices = ""
gas-adjustment = ""

# Fees to use instead of set gas prices
fees = ""
fee-granter = ""
fee-payer = ""

# Memo to include in your Transactions
note = ""
