# This configuration file contains settings for all WAVS components:
# - General settings (shared across all processes)
# - WAVS server-specific settings
# - CLI-specific settings
# - Aggregator-specific settings
#
# Environment variable overrides follow these patterns:
# - WAVS server settings: WAVS_<UPPERCASE_KEY>
# - CLI settings: WAVS_CLI_<UPPERCASE_KEY>
# - Aggregator settings: WAVS_AGGREGATOR_<UPPERCASE_KEY>
#
# For arrays, use a comma-separated list in a single string:
# e.g., WAVS_LOG_LEVEL="info, wavs=debug" or WAVS_CORS_ALLOWED_ORIGINS="https://example.com, https://example2.com"

# ----------------------------
# Default settings (shared)
# ----------------------------
# The log level, in the format of tracing directives. Default is ["info"]
# See https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#directives
[default]
log_level = ["info", "wavs=debug"]

# Those configs are global and shared between wavs and aggregator
# jaeger = "http://localhost:4317"
# prometheus = "http://localhost:9090"


# ----------------------------
# Chain configurations
# ----------------------------

# == Ethereum chains ==

# Mainnet
[default.chains.evm.ethereum]
chain_id = "1"
ws_endpoint = "wss://eth.drpc.org"
http_endpoint = "https://eth.drpc.org"

[default.chains.evm.base]
chain_id = "8453"
ws_endpoint = "wss://base.drpc.org"
http_endpoint = "https://base.drpc.org"

[default.chains.evm.optimism]
chain_id = "10"
ws_endpoint = "wss://optimism.drpc.org"
http_endpoint = "https://optimism.drpc.org"

[default.chains.evm.arbitrum]
chain_id = "42161"
ws_endpoint = "wss://arbitrum.drpc.org"
http_endpoint = "https://arbitrum.drpc.org"

# Local / Testnet
[default.chains.evm.local]
chain_id = "31337"
ws_endpoint = "ws://localhost:8545"
http_endpoint = "http://localhost:8545"
poll_interval_ms = 7000

[default.chains.evm.local2]
chain_id = "31338"
ws_endpoint = "ws://localhost:8645"
http_endpoint = "http://localhost:8645"
poll_interval_ms = 7000

[default.chains.evm.sepolia]
chain_id = "11155111"
ws_endpoint = "wss://ethereum-sepolia-rpc.publicnode.com"
http_endpoint = "https://ethereum-sepolia-rpc.publicnode.com"

[default.chains.evm.holesky]
chain_id = "17000"
ws_endpoint = "wss://ethereum-holesky-rpc.publicnode.com"
http_endpoint = "https://ethereum-holesky-rpc.publicnode.com"

[default.chains.evm.holesky-fork]
chain_id = "17000"
ws_endpoint = "ws://localhost:8545"
http_endpoint = "http://localhost:8545"
poll_interval_ms = 7000

# == Cosmos chains ==

[default.chains.cosmos.neutron]
chain_id = "pion-1"
bech32_prefix = "neutron"
rpc_endpoint = "https://rpc-falcron.pion-1.ntrn.tech"
grpc_endpoint = "http://grpc-falcron.pion-1.ntrn.tech:80"
gas_price = 0.0053
gas_denom = "untrn"

# ----------------------------
# WAVS specific settings
# ----------------------------
[wavs]

# The directory to store the data. Default is "/var/wavs"
data = "~/wavs"

cors_allowed_origins = [
    "https://lay3rlabs.github.io/*",
    "http://localhost:*",
    "http://127.0.0.1:*",
]

# The port on which the server will listen.
# port = 8000

# The host to serve on. Default is localhost
# host = "localhost"

# WAVS-specific chain overrides (if needed)
# Example:
# [wavs.chains.evm.local]
# chain_id = "31337"
# ws_endpoint = "ws://localhost:8545"
# http_endpoint = "http://localhost:8545"

# ----------------------------
# CLI specific settings
# ----------------------------
[cli]
# The directory to store the data. Default is "/var/wavs-cli"
data = "~/wavs/cli"

# wavs_endpoint = "http://localhost:8000"

# ----------------------------
# Aggregator specific settings
# ----------------------------
[aggregator]
# The directory to store the data. Default is "/var/wavs-aggregator"
data = "~/wavs"

cors_allowed_origins = [
    "https://lay3rlabs.github.io/*",
    "http://localhost:*",
    "http://127.0.0.1:*",
]

# Aggregator-specific chain overrides (if needed)
# Example:
# [aggregator.chains.evm.local]
# chain_id = "31337"
# ws_endpoint = "ws://localhost:8545"
# http_endpoint = "http://localhost:8545"
