services:
  cosmos-node:
    image: "ghcr.io/bitsongofficial/go-bitsong:v0.22.0"
    container_name: "bitsong-node"
    # network_mode: "host"
    ports:
      - "26656:26656" # P2P port  
      - "26657:26657" # RPC port  
      - "1317:1317"   # REST API 
    environment:
      - MONIKER=Bitsong Node
    volumes:
      - "../../.cosmos/data:/.cosmos/data"
      - "./cosmos-entrypoint.sh:/cosmos-entrypoint.sh"  
    entrypoint: ["sh", "-c", "/cosmos-entrypoint.sh"]
    # command: sh -c "chmod +x ./cosmos-entrypoint.sh && ./cosmos-entrypoint.sh"