[package]
name = "cw-orch-wavs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


env_logger = { version = "0.11.3", default-features = false }
anyhow = "1.0.79"
dotenv = "0.15.0"
reqwest                      = { version = "0.11.9" }
clap = "4.5.23"
tokio = "1.39.3"
prost-types                  = "0.12.6"
log                          = "0.4.22"

#  cosmos 
cosmrs = "0.15.0"
cosmos-sdk-proto = "0.24.0"
cosmwasm-schema            = { workspace = true }
cosmwasm-std   = { workspace = true }
cosmwasm-crypto  = { version = "2.1.4",  default-features = false }
cw721 = "0.18.0"
cw-orch = { version = "0.24.1", features = ["daemon"] }
cw-orch-clone-testing = "0.6.4"
# cw-infuser = {version = "0.4.2", path = "../contracts/cw-infuser" }
# cw-infusions = {  path = "../packages/cw-infusions" }
sg721 = "^3.3"
sg721-base = "^3.3"

# eth 

# wavs