# TODO: re-enable for 0.4 official

# name: Docs CI

# # based on https://docs.wavs.xyz/ & this repos README.md

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#   workflow_dispatch:

# # Ensures that only a single workflow per PR will run at a time. Cancels in-progress jobs if new commit is pushed.
# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

# env:
#   GO_VERSION: 1.23.7

# jobs:
#   run:
#     runs-on: ubuntu-latest
#     env:
#       DEBUGGING: true

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4

#     - name: Install Ubuntu packages
#       run: sudo apt-get update && sudo apt-get install bash make jq

#     - uses: actions/setup-node@v4
#       name: Install Node.js
#       with:
#         node-version: 21

#     - name: Set up Go ${{ env.GO_VERSION }}
#       uses: actions/setup-go@v4
#       with:
#         go-version: ${{ env.GO_VERSION }}

#     - name: Install Rust
#       uses: actions-rs/toolchain@v1
#       with:
#         profile: minimal
#         toolchain: stable
#         override: true

#     - name: Cache Rust target
#       uses: actions/cache@v3
#       with:
#         path: |
#           ~/.rustup/toolchains
#           ~/.cargo/bin/
#           ~/.cargo/registry/index/
#           ~/.cargo/registry/cache/
#           ~/.cargo/git/db/
#           target/
#         key: ${{ runner.os }}-rust-wasm32-${{ hashFiles('**/Cargo.lock') }}
#         restore-keys: |
#           ${{ runner.os }}-rust-wasm32-

#     - uses: cargo-bins/cargo-binstall@main
#       name: Install cargo-binstall

#     - name: Install Foundry
#       uses: foundry-rs/foundry-toolchain@v1
#       with:
#         version: stable

#     - name: Install rust wasm32-wasip2
#       run: rustup target add wasm32-wasip2

#     - name: Check if wkg exists
#       id: check-wkg
#       run: |
#         if [ ! -f ~/.cargo/bin/wkg ]; then
#           echo "wkg_exists=false" >> $GITHUB_OUTPUT
#         else
#           echo "wkg_exists=true" >> $GITHUB_OUTPUT
#         fi

#     # limited due to low rate limits
#     - name: Install wasi components
#       if: steps.check-wkg.outputs.wkg_exists == 'false'
#       run: cargo binstall cargo-component warg-cli wkg --locked --no-confirm --force

#     - name: Configure wkg registry
#       run: wkg config --default-registry wa.dev

#     - name: Install docci readme runner
#       run: |
#         RELEASE=https://github.com/Reecepbcups/docci/releases/download/v0.7.1/docci
#         sudo wget --quiet -O /usr/local/bin/docci ${RELEASE}
#         sudo chmod a+rx /usr/local/bin/docci


#     # installs wasm-tools as well, required for rust & ts
#     - name: Run docci (go)
#       run: docci components/golang-evm-price-oracle/config.json

#     - name: Run docci (rust)
#       run: docci components/evm-price-oracle/config.json

#     # - name: Run docci (typescript)
#       # run: docci components/js-evm-price-oracle/config.json
